
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.108.187:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: hello
          uri: lb://hello-consumer
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1
        - id: login
          uri: lb://login-consumer
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1